name: EvoX

on:
  workflow_dispatch:

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure wget is installed and Download EvolutionX ZIP
        run: |
          if ! command -v wget &> /dev/null; then
            echo "wget not found, installing..."
            sudo apt update
            sudo apt install -y wget
          fi
          wget -O EvolutionX-15.0-20250302-d2x-10.3-Official.zip https://sourceforge.net/projects/evolution-x/files/d2x/15/EvolutionX-15.0-20250302-d2x-10.3-Official.zip/download

      - name: Upload EvolutionX ZIP as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: EvolutionX-15.0-20250302-d2x-10.3-Official
          path: EvolutionX-15.0-20250302-d2x-10.3-Official.zip
