name: Dlp Pipe Test

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'Video URL to download'
        required: true
      downloader:
        description: 'Downloader option'
        default: none
        type: choice
        options:
          - none
          - ffmpeg
          - aria2c
      proxy:
        description: 'Use proxy'
        default: true
        type: choice
        options:
          - true
          - false

jobs:
  download_upload:
    runs-on: ubuntu-latest

    env:
      VIDEO_LINK: ${{ github.event.inputs.video_link }}
      DOWNLOADER: ${{ github.event.inputs.downloader }}
      PROXY: ${{ github.event.inputs.proxy }}
      GOFILE_TOKEN: ${{ secrets.GOFILE_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Sing-box (if proxy enabled)
        if: env.PROXY == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
          sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y sing-box=1.12.1

      - name: Setup Sing-box (if proxy enabled)
        if: env.PROXY == 'true'
        run: |
          sudo rm -f /etc/sing-box/config.json
          sudo cp create.sh /etc/sing-box/
          cd /etc/sing-box
          sudo chmod +x create.sh
          sudo ./create.sh
          sudo systemctl disable sing-box
          sleep 2
          sudo ENABLE_DEPRECATED_TUN_ADDRESS_X=true nohup sing-box run -c /etc/sing-box/config.json > sing-box.log 2>&1 &
          curl ifconfig.me

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip ffmpeg aria2
          pip3 install --upgrade yt-dlp requests

      - name: Download Video
        run: |
          mkdir -p downloads
          DOWNLOAD_PATH=$(yt-dlp -f best --restrict-filenames -o 'downloads/%(title)s.%(ext)s' "${VIDEO_LINK}")
          echo "DOWNLOAD_PATH=$DOWNLOAD_PATH" >> $GITHUB_ENV

      - name: Upload Video
        run: |
          python3 dlp_pipe_test.py
