name: Run app.py

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Create directory and clone repository
      run: |
        mkdir -p CodeFormer
        git lfs install
        git lfs clone https://huggingface.co/spaces/sczhou/CodeFormer CodeFormer

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Find CodeFormer directory
      id: find-directory
      run: |
        directory=$(find . -type d -name "CodeFormer" -print -quit)
        echo "CodeFormer directory found at: $directory"
        echo "::set-output name=directory::$directory"

    - name: Set working directory
      run: cd ${{ steps.find-directory.outputs.directory }}

    - name: Verify contents of CodeFormer directory
      run: ls -la

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run app.py
      run: |
        chmod +x app.py
        ./app.py
