name: Run app.py

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      run: |
        git lfs install
        git lfs clone https://huggingface.co/spaces/sczhou/CodeFormer
      working-directory: ${{ github.workspace }}/CodeFormer

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r CodeFormer/requirements.txt

    - name: Run app.py
      run: |
        chmod +x CodeFormer/app.py
        CodeFormer/app.py
