 name: Set up SSH server and user
  run: |
    # Create user "admin" with password "abcd1234" and grant sudo privileges
    sudo useradd -m -s /bin/bash admin
    echo 'admin:abcd1234' | sudo chpasswd
    sudo usermod -aG sudo admin

    # Install OpenSSH server
    sudo apt update
    sudo apt install -y openssh-server

    # Allow password authentication in SSH
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

    # Restart SSH server
    sudo service ssh restart

    # Get the public IP address
    public_ip=$(curl -s https://api64.ipify.org?format=json | jq -r .ip)

    echo "SSH Server is running at:"
    echo "Username: admin"
    echo "Password: abcd1234"
    echo "Connect using: ssh admin@$public_ip"
