name: test latest ffmpeg

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'link to test'
        required: true
      preset:
        description: 'FFmpeg preset (optional)'
        default: slower
        type: choice
        options:
          - ultrafast
          - superfast
          - veryfast
          - faster
          - fast
          - medium
          - slow
          - slower
          - veryslow
      fps:
        description: 'Frames per second (optional)'
        default: 24
      crf:
        description: 'Constant rate factor (optional) (0–63) lower means higher quality, (17–28) sane range'
        default: 28
      encoder:
        description: 'FFmpeg encoder (optional)'
        default: libx264
        type: choice
        options:
          - libx264
          - libx265
          - libvpx-vp9
          - libaom-av1
      aname:
        description: 'Name of the artifact zip (optional)'
        default: video1

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Display System Information
        run: |
          sudo apt-get update
          sudo apt-get install -y neofetch
          neofetch

      - name: Cloudflare WARP Setup
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp
          sudo warp-cli --accept-tos register

      - name: Create Directories
        run: |
          mkdir -p videos
          mkdir -p artifacts

      - name: Install Dependencies
        run: |
          sudo apt-get install -y ffmpeg
          sudo pip install --upgrade yt-dlp

      - name: Download Video
        id: download_videos
        run: |
          sudo warp-cli --accept-tos connect
          cd videos
          yt-dlp -J --flat-playlist ${{ github.event.inputs.video_link }} > playlist_info.json

      - name: Process Videos
        run: |
          cd videos
          jq -r '.entries | .[] | "\(.url)"' playlist_info.json | while read -r video_url; do
            echo "Processing video: $video_url"
            sudo nice -n -20 yt-dlp -o "input_video.%(ext)s" "$video_url"
            VIDEO_TITLE=$(yt-dlp --get-title "$video_url" | sed 's/[^a-zA-Z0-9]/_/g')
            sudo nice -n -20 ffmpeg -i input_video.* -c:v ${{ github.event.inputs.encoder }} -preset ${{ github.event.inputs.preset }} -vf fps=${{ github.event.inputs.fps }} -crf ${{ github.event.inputs.crf }} -max_muxing_queue_size 9999 -c:a aac -strict experimental "${VIDEO_TITLE}_${RANDOM}.mp4"
            rm -rf input_video.*
          done

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.aname }}_${{ matrix.video_index }}
          compression-level: 9
          path: videos/*.mp4
