name: Remote Desktop Workflow

on:
  push:
    branches:
      - main

jobs:
  remote-desktop:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up VNC Server
      run: |
        # Install Chocolatey for package management
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

        # Install VNC Server
        choco install -y tightvnc

        # Start VNC Server
        Start-Process "C:\Program Files\TightVNC\tvnserver.exe" -NoNewWindow
        Start-Sleep -Seconds 5  # Allow time for the server to start

        # Get IP address and port
        $ipAddress = (Test-NetConnection -ComputerName localhost -Port 5900).RemoteAddress
        Write-Output "VNC Server is running at $ipAddress:5900"

    - name: Sleep and repeat
      run: |
        # Adjust sleep time (seconds) and loop count as needed
        for ($i=1; $i -le 10; $i++) {
          Start-Sleep -Seconds 300  # Sleep for 5 minutes
          
          # Restart VNC Server
          Stop-Process -Name "tvnserver" -Force
          Start-Process "C:\Program Files\TightVNC\tvnserver.exe" -NoNewWindow
          
          # Get updated IP address and port
          $ipAddress = (Test-NetConnection -ComputerName localhost -Port 5900).RemoteAddress
          Write-Output "VNC Server is running at $ipAddress:5900"
        }
