name: test latest ffmpeg

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'link to test'
        required: true
      preset:
        description: 'FFmpeg preset (optional)'
        default: slower
        type: choice
        options:
          - ultrafast
          - superfast
          - veryfast
          - faster
          - fast
          - medium
          - slow
          - slower
          - veryslow
      fps:
        description: 'Frames per second (optional)'
        default: 24
      crf:
        description: 'Constant rate factor (optional) (0–63) lower means higher quality, (17–28) sane range'
        default: 28
      encoder:
        description: 'FFmpeg encoder (optional)'
        default: libx264
        type: choice
        options:
          - libx264
          - libx265
          - libvpx-vp9
          - libaom-av1
      aname:
        description: 'Name of the artifact zip (optional)'
        default: video1

jobs:
  process_video:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        machine:
          - first-machine

    env:
      VIDEO_LINK: ${{ github.event.inputs.video_link }}
      PRESET: ${{ github.event.inputs.preset }}
      FPS: ${{ github.event.inputs.fps }}
      CRF: ${{ github.event.inputs.crf }}
      ENCODER: ${{ github.event.inputs.encoder }}
      ANAME: ${{ github.event.inputs.aname }}
      ENABLE_DEPRECATED_TUN_ADDRESS_X: true
      

    steps:
      - name: Display System Information
        run: |
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
          sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y neofetch sing-box=1.11.4
          neofetch
      - name: sing-box setup
        run: |
          sudo rm -f /etc/sing-box/config.json
          sudo curl -sSL 'https://github.com/Cat-Ling/ignore/raw/refs/heads/main/config.json' -o /etc/sing-box/config.json
          sudo systemctl disable sing-box
          sleep 2
          sudo ENABLE_DEPRECATED_TUN_ADDRESS_X=true nohup sing-box run -c /etc/sing-box/config.json > sing-box.log 2>&1 &
          curl https://ifconfig.me/ip
      - name: Create Directories
        run: |
          mkdir -p videos
          mkdir -p artifacts
      - name: Install Dependencies
        run: |
          sudo apt-get install -y ffmpeg
          sudo apt install -y yt-dlp
          echo used to be sudo pip install --upgrade yt-dlp --break-system-packages
      - name: Download Video
        run: |
          cd videos
          sudo nice -n -20 yt-dlp --concurrent-fragments 10 -o "input_video.%(ext)s" "$VIDEO_LINK"
      - name: Convert Video with H.264 Compression
        run: |
          cd videos
          VIDEO_TITLE=$(yt-dlp --get-title "$VIDEO_LINK" | sed 's/[^a-zA-Z0-9]/_/g')
          sudo nice -n -20 ffmpeg -thread_queue_size 2048 -i input_video.* -c:v $ENCODER -preset $PRESET -vf fps=$FPS -crf $CRF -max_muxing_queue_size 9999 -c:a aac -threads 4 -bufsize 16M -strict experimental "${VIDEO_TITLE}.mp4"
          rm -rf input_video.*
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.aname }}
          compression-level: 9
          path: videos/*.mp4
