on:
  push:
    branches:
      - main

jobs:
  process_video:
    runs-on: ubuntu-20.04

    env:
      VIDEO_LINK: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      QUALITY: "1080p"
      FORMAT_OPTIONS: "--merge-output-format mp4"

    steps:
    - name: Display System Information and Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y neofetch ffmpeg
        pip install --upgrade yt-dlp
        neofetch

    - name: Create Directories
      run: mkdir -p videos artifacts

    - name: Download Video and Convert with H.264 Compression
      run: |
        cd videos
        # Available yt-dlp quality options:
        # - best, worst
        # - bestvideo, bestaudio, worstvideo, worstaudio
        # - bestvideo[height<=1080], bestaudio/best[height<=1080]
        INFO=$(yt-dlp --get-title --get-id -o "%(title)s.%(ext)s" $VIDEO_LINK)
        yt-dlp --format "bestvideo[height<=$QUALITY]+bestaudio/best[height<=$QUALITY]" $FORMAT_OPTIONS -o "$INFO" $VIDEO_LINK

        # Wait for yt-dlp to finish merging before starting ffmpeg
        wait $(jobs -p)

        ffmpeg -i "$INFO" -c:v libx264 -crf 28 -preset ultrafast -max_muxing_queue_size 1024 -c:a copy output_video.mkv

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: processed-video
        path: videos/"$INFO"
