name: SSH Server Setup

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH server
      run: |
        sudo bash -E << 'SCRIPT'
        # Function to check if user exists
        user_exists() {
          id "$1" &>/dev/null
        }

        # Loop until user "admin" is successfully created
        while ! user_exists "admin"; do
          # Create user "admin" with password "abcd1234" and grant sudo privileges
          sudo useradd -m -s /bin/bash admin
          echo 'admin:abcd1234' | sudo chpasswd
          sudo usermod -aG sudo admin

          sleep 5  # Give the system a moment to process

          if user_exists "admin"; then
            break
          fi

          echo "Retrying user creation..."
        done

        # Install OpenSSH server
        sudo apt update
        sudo apt install -y openssh-server

        # Allow password authentication in SSH
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

        # Restart SSH server
        sudo service ssh restart

        # Get the public IP address
        public_ip=$(curl -s https://api64.ipify.org?format=json | jq -r .ip)

        echo "SSH Server is running at:"
        echo "Username: admin"
        echo "Password: abcd1234"
        echo "Connect using: ssh admin@$public_ip"
        SCRIPT
