name: Run app.py

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: https://huggingface.co/spaces/sczhou/CodeFormer
        ref: main
        fetch-depth: 0

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run app.py
      run: |
        chmod +x app.py
        pip install -r requirements.txt
        ./app.py
