name: Remote Desktop Workflow

on:
  push:
    branches:
      - main

jobs:
  remote-desktop:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up VNC Server
      run: |
        # Install Chocolatey for package management
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

        # Install VNC Server
        choco install -y tightvnc

        # Start VNC Server with dynamically fetched public IP
        $publicIpAddress = (Invoke-RestMethod -Uri https://api64.ipify.org?format=json).ip
        Start-Process "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-interface $publicIpAddress" -NoNewWindow
        Start-Sleep -Seconds 30  # Adjust timing as needed

        # Get updated IP address and port
        Write-Output "VNC Server is running at $publicIpAddress:5900"

    - name: Sleep and repeat
      run: |
        # Adjust sleep time (seconds) and loop count as needed
        for ($i=1; $i -le 10; $i++) {
          Start-Sleep -Seconds 300  # Sleep for 5 minutes
          
          # Restart VNC Server
          Stop-Process -Name "tvnserver" -Force
          $publicIpAddress = (Invoke-RestMethod -Uri https://api64.ipify.org?format=json).ip
          Start-Process "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-interface $publicIpAddress" -NoNewWindow
          
          # Get updated IP address and port
          Write-Output "VNC Server is running at $publicIpAddress:5900"
        }
