name: test latest ffmpeg

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: 'link to test'
        required: true
      downloader:
        description: 'Downloader option'
        default: none
        type: choice
        options:
          - none
          - ffmpeg
          - aria2c
      preset:
        description: 'FFmpeg preset (optional)'
        default: slower
        type: choice
        options:
          - ultrafast
          - superfast
          - veryfast
          - faster
          - fast
          - medium
          - slow
          - slower
          - veryslow
      fps:
        description: 'Frames per second (optional)'
        default: 24
      crf:
        description: 'Constant rate factor (optional) (0–63) lower means higher quality, (17–28) sane range'
        default: 28
      encoder:
        description: 'FFmpeg encoder (optional)'
        default: libx264
        type: choice
        options:
          - libx264
          - libx265
          - libvpx-vp9
          - libaom-av1
      aname:
        description: 'Name of the artifact zip (optional)'
        default: video1
      proxy:
        description: 'Use Proxy'
        default: true
        type: choice
        options:
          - true
          - false

jobs:
  process_video:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        machine:
          - first-machine

    env:
      VIDEO_LINK: ${{ github.event.inputs.video_link }}
      DOWNLOADER: ${{ github.event.inputs.downloader }}
      PRESET: ${{ github.event.inputs.preset }}
      FPS: ${{ github.event.inputs.fps }}
      CRF: ${{ github.event.inputs.crf }}
      ENCODER: ${{ github.event.inputs.encoder }}
      ANAME: ${{ github.event.inputs.aname }}
      ENABLE_DEPRECATED_TUN_ADDRESS_X: true
      PROXY: ${{ github.event.inputs.proxy }}
      
    steps:
      - name: Install Sing-box (if proxy is enabled)
        if: env.PROXY == 'true'
        run: |
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
          sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y sing-box=1.12.1
      
      - name: Setup Sing-box (if proxy is enabled)
        if: env.PROXY == 'true'
        run: |
          sudo rm -f /etc/sing-box/config.json
          sudo curl -sSL 'https://raw.githubusercontent.com/Cat-Ling/sing-box/refs/heads/main/config.json' -o /etc/sing-box/config.json
          sudo systemctl disable sing-box
          sleep 2
          sudo ENABLE_DEPRECATED_TUN_ADDRESS_X=true nohup sing-box run -c /etc/sing-box/config.json > sing-box.log 2>&1 &
          curl ifconfig.me
      
      - name: Create Directories
        run: |
          mkdir -p videos
          mkdir -p artifacts
      
      - name: Install Dependencies
        run: |
          sudo apt-get install -y ffmpeg
          sudo apt-get install -y yt-dlp
          echo used to be sudo pip install --upgrade yt-dlp --break-system-packages
          sudo apt-get install -y aria2
      
      - name: Download Video
        run: |
          cd videos
          if [ "$DOWNLOADER" == "ffmpeg" ]; then
            sudo nice -n -20 yt-dlp --concurrent-fragments 12 --downloader ffmpeg -o "input_video.%(ext)s" "$VIDEO_LINK"
          elif [ "$DOWNLOADER" == "aria2c" ]; then
            sudo nice -n -20 yt-dlp --concurrent-fragments 32 --downloader aria2c -o "input_video.%(ext)s" "$VIDEO_LINK"
          else
            sudo nice -n -20 yt-dlp --concurrent-fragments 32 -o "input_video.%(ext)s" "$VIDEO_LINK"
          fi
          
      - name: Upload initial file to Artifacts for comparison
        uses: actions/upload-artifact@v4
        with:
          name: original_${{ github.event.inputs.aname }}
          compression-level: 9
          path: videos/*.mp4
          
      - name: Encoding
        run: |
          cd videos
          VIDEO_TITLE=$(yt-dlp --get-title "$VIDEO_LINK" | sed 's/[^a-zA-Z0-9.-]/_/g')
          sudo nice -n -20 ffmpeg -i input_video.* -c:v $ENCODER -preset $PRESET -crf $CRF -c:a aac -b:a 128k  -vf fps=$FPS "${VIDEO_TITLE}.mp4" -strict experimental -threads 4 -bufsize 16M -thread_queue_size 2048
          rm -rf input_video.*
      
      - name: Upload results to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.aname }}
          compression-level: 9
          path: videos/*.mp4
