name: Video Processing Workflow

on:
  push:
    branches:
      - main

jobs:
  process_video:
    runs-on: ubuntu-latest

    env:
      VIDEO_LINK: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"  # Replace with your desired video link

    steps:
    - name: Display System Information
      run: |
        sudo apt-get update
        sudo apt-get install -y neofetch
        neofetch

    - name: Create Directories
      run: |
        mkdir -p videos
        mkdir -p artifacts

    - name: Install Dependencies
      run: |
        sudo apt-get install -y ffmpeg
        pip install --upgrade yt-dlp

    - name: Download Video
      run: |
        cd videos
        yt-dlp -o "input_video.%(ext)s" $VIDEO_LINK
      
    - name: Convert Video with AV1 Compression
      run: |
        cd videos
        ffmpeg -i input_video.* -c:v libaom-av1 -b:v 0 -crf 30 -c:a copy output_video.mkv

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: processed-video
        path: videos/output_video.mkv
